<a href="https://colab.research.google.com/github/rahulrajpr/AdvancedFeatureEngineering/blob/Scalling/ScallingToVectorUnitLegth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Scalling to vector unint length

Scales the dataset not by varaible by varible

Scales the dataset observarion by observation (row by roe)

Two Method

- L1 - Manhattam Distance - Sum of all the variable in a row
- L2 - Euclidean Distance - Sqrt( sum of squared of all the variables in a row)

Process 

- Divide all the variables in a row by either the L1 or L2 of the row
- After scaling the L1 value or L2 value of all the rows will be 1, according to which method is used using the scalling process

In [33]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [34]:
from sklearn.datasets import load_boston

In [35]:
boston = load_boston()

In [36]:
data = pd.DataFrame(data = boston.data, columns = boston.feature_names)

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB


In [38]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [39]:
target = pd.Series(boston.target).rename('MEDV')

In [40]:
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [41]:
data.describe().loc['mean']

CRIM         3.613524
ZN          11.363636
INDUS       11.136779
CHAS         0.069170
NOX          0.554695
RM           6.284634
AGE         68.574901
DIS          3.795043
RAD          9.549407
TAX        408.237154
PTRATIO     18.455534
B          356.674032
LSTAT       12.653063
Name: mean, dtype: float64

In [42]:
data.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
dtype: int64

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train,X_test, y_train, y_test = train_test_split(data,target, train_size = 0.7, random_state = 100)

In [45]:
from sklearn.preprocessing import Normalizer

## By Manhattam Distance of the vector - L1

In [46]:
scaler = Normalizer(norm = 'l1')

In [47]:
scaler.fit(X_train)

Normalizer(norm='l1')

In [48]:
scaler.transform(X_train)

array([[4.70145690e-03, 0.00000000e+00, 1.46184809e-02, ...,
        1.63145477e-02, 3.18069068e-01, 8.31072752e-03],
       [1.07721142e-04, 0.00000000e+00, 1.45296704e-02, ...,
        2.11773060e-02, 4.33998876e-01, 1.01243377e-02],
       [8.23957824e-03, 0.00000000e+00, 1.45740610e-02, ...,
        1.62649741e-02, 3.05733202e-01, 1.45176972e-02],
       ...,
       [3.51666418e-04, 0.00000000e+00, 9.14094875e-03, ...,
        2.42767745e-02, 4.84457898e-01, 1.45412925e-02],
       [4.91623048e-05, 2.74803269e-02, 4.57547443e-03, ...,
        2.04728435e-02, 5.32170271e-01, 5.16630146e-03],
       [2.39887799e-04, 1.41952163e-02, 8.93730818e-03, ...,
        1.72613830e-02, 4.39063718e-01, 3.39890259e-02]])

In [49]:
X_train_scaled = pd.DataFrame(data = scaler.transform(X_train), columns = X_train.columns)
X_test_scaled = pd.DataFrame(data = scaler.transform(X_test), columns = X_test.columns)

In [50]:
# Manhattan Distance before Scalling
X_train.sum(axis = 1)

463    1238.15875
75      883.02072
478    1241.93250
199     950.29290
84      739.17799
          ...    
343     924.79753
359    1226.66241
323     807.35602
280     727.79338
8       880.57834
Length: 354, dtype: float64

In [51]:
# Manhattan Distance After Scalling
X_train_scaled.sum(axis = 1)

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
349    1.0
350    1.0
351    1.0
352    1.0
353    1.0
Length: 354, dtype: float64

## By Euclidean Distance of the vector - L2

In [52]:
X_train,X_test, y_train, y_test = train_test_split(data,target, train_size = 0.7, random_state = 100)

In [53]:
scaler = Normalizer(norm = 'l2')

In [54]:
scaler.fit(X_train)

Normalizer()

In [55]:
scaler.transform(X_train)

array([[7.46402871e-03, 0.00000000e+00, 2.32082870e-02, ...,
        2.59009611e-02, 5.04966164e-01, 1.31941035e-02],
       [1.71401733e-04, 0.00000000e+00, 2.31190520e-02, ...,
        3.36965139e-02, 6.90562300e-01, 1.61094564e-02],
       [1.32232727e-02, 0.00000000e+00, 2.33891563e-02, ...,
        2.61028153e-02, 4.90655395e-01, 2.32987010e-02],
       ...,
       [5.77712166e-04, 0.00000000e+00, 1.50166095e-02, ...,
        3.98815105e-02, 7.95859958e-01, 2.38882109e-02],
       [7.96921663e-05, 4.45456491e-02, 7.41685058e-03, ...,
        3.31865086e-02, 8.62648769e-01, 8.37458204e-03],
       [4.16166528e-04, 2.46264041e-02, 1.55047840e-02, ...,
        2.99457073e-02, 7.61704528e-01, 5.89654619e-02]])

In [56]:
X_train_scaled = pd.DataFrame(data = scaler.transform(X_train), columns = X_train.columns)
X_test_scaled = pd.DataFrame(data = scaler.transform(X_test), columns = X_test.columns)

In [59]:
# Manhattan Distance before Scalling
X_train.apply(lambda x : np.sqrt(sum([a**2 for a in x])), axis = 1)

463    779.893838
75     554.953550
478    773.862887
199    573.429196
84     470.500192
          ...    
343    548.738644
359    777.417533
323    491.455809
280    448.977630
8      507.585272
Length: 354, dtype: float64

In [60]:
# Manhattan Distance After Scalling
X_train_scaled.apply(lambda x : np.sqrt(sum([a**2 for a in x])), axis = 1)

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
349    1.0
350    1.0
351    1.0
352    1.0
353    1.0
Length: 354, dtype: float64