<a href="https://colab.research.google.com/github/rahulrajpr/AdvancedFeatureEngineering/blob/DateTimeEngineering/DateTimeEngineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [291]:
import pandas as pd
import numpy as np
import datetime
import warnings
warnings.filterwarnings('ignore')

In [292]:
path = '/content/drive/MyDrive/Udemy Courses - 2.0/Feature Engineering/Dataset/loan.csv'
data = pd.read_csv(path)

In [293]:
sel_cols = ['date_issued', 'date_last_payment']

In [294]:
data = data[sel_cols]

In [295]:
data.columns = ['issue','payment']

In [296]:
data.dtypes

issue      object
payment    object
dtype: object

In [297]:
pd.to_datetime(data['issue'])

0      2013-06-11
1      2014-05-08
2      2013-10-26
3      2015-08-20
4      2014-07-22
          ...    
9995   2010-01-14
9996   2015-03-20
9997   2015-04-03
9998   2014-11-23
9999   2015-01-19
Name: issue, Length: 10000, dtype: datetime64[ns]

In [298]:
data['issue'] = pd.to_datetime(data['issue'])
data['payment'] = pd.to_datetime(data['payment'])

In [299]:
data.dtypes

issue      datetime64[ns]
payment    datetime64[ns]
dtype: object

### Extracting the Elements from a date variable

In [300]:
# Extract the date as string from the datetime object
data['date'] = data['payment'].dt.date
data['date']

0       2016-01-14
1       2016-01-25
2       2014-09-26
3       2016-01-26
4       2016-01-11
           ...    
9995    2010-11-03
9996    2016-01-26
9997    2015-12-12
9998    2016-01-01
9999    2016-01-16
Name: date, Length: 10000, dtype: object

In [301]:
# Extract the time as string from the datetime object
data['time'] = data['payment'].dt.time
data['time']

0       00:00:00
1       00:00:00
2       00:00:00
3       00:00:00
4       00:00:00
          ...   
9995    00:00:00
9996    00:00:00
9997    00:00:00
9998    00:00:00
9999    00:00:00
Name: time, Length: 10000, dtype: object

In [302]:
# year from the date element
data['y'] = data['payment'].dt.year
data['y']

0       2016
1       2016
2       2014
3       2016
4       2016
        ... 
9995    2010
9996    2016
9997    2015
9998    2016
9999    2016
Name: y, Length: 10000, dtype: int64

In [303]:
data['y'].unique()

array([2016, 2014, 2015, 2012, 2011, 2013, 2010, 2008, 2009])

In [304]:
# quarter from the date element
data['q'] = data['payment'].dt.quarter
data['q']

0       1
1       1
2       3
3       1
4       1
       ..
9995    4
9996    1
9997    4
9998    1
9999    1
Name: q, Length: 10000, dtype: int64

In [305]:
data['q'].unique()

array([1, 3, 4, 2])

In [306]:
# semester from the date element
data['sem'] = data['payment'].dt.quarter.apply(lambda x : 1 if x in([1,2]) else 2)
data['sem']

0       1
1       1
2       2
3       1
4       1
       ..
9995    2
9996    1
9997    2
9998    1
9999    1
Name: sem, Length: 10000, dtype: int64

In [307]:
data['sem'].unique()

array([1, 2])

In [308]:
# month from the date element
data['m_num'] = data['payment'].dt.month
data['m_num']

0        1
1        1
2        9
3        1
4        1
        ..
9995    11
9996     1
9997    12
9998     1
9999     1
Name: m_num, Length: 10000, dtype: int64

In [309]:
data['m_num'].unique()

array([ 1,  9,  8, 12,  6, 11,  4, 10,  7,  2,  5,  3])

In [310]:
# month_name from the date element
data['m_name'] = data['payment'].dt.month_name() # note the braces for month names which is different from all other attributes
data['m_name']

0         January
1         January
2       September
3         January
4         January
          ...    
9995     November
9996      January
9997     December
9998      January
9999      January
Name: m_name, Length: 10000, dtype: object

In [311]:
data['m_name'].unique()

array(['January', 'September', 'August', 'December', 'June', 'November',
       'April', 'October', 'July', 'February', 'May', 'March'],
      dtype=object)

In [312]:
# weekno from the date element
data['week_num'] = data['payment'].dt.week
data['week_num']

0        2
1        4
2       39
3        4
4        2
        ..
9995    44
9996     4
9997    50
9998    53
9999     2
Name: week_num, Length: 10000, dtype: int64

In [313]:
data['week_num'].unique()

array([ 2,  4, 39, 53,  1, 31,  3, 51, 49, 52, 26, 48, 15, 50, 32, 41, 38,
       43, 28, 16, 23, 46, 25,  7, 17, 22,  9, 19, 37, 42, 21, 18, 11, 36,
       29, 12, 33, 47, 30, 34, 45, 10,  5, 13, 40, 27,  6, 44, 20, 35, 24,
        8, 14])

In [314]:
data['d'] = data['payment'].dt.day
data['d']

0       14
1       25
2       26
3       26
4       11
        ..
9995     3
9996    26
9997    12
9998     1
9999    16
Name: d, Length: 10000, dtype: int64

In [315]:
data['d'].unique()

array([14, 25, 26, 11, 10,  2,  1,  8, 20, 18,  3,  6, 17, 12, 23, 15,  7,
       22, 13,  9, 27, 21, 16, 19, 24,  4,  5])

In [316]:
data['dayofweek_num'] = data['payment'].dt.dayofweek
data['dayofweek_num']

0       3
1       0
2       4
3       1
4       0
       ..
9995    2
9996    1
9997    5
9998    4
9999    5
Name: dayofweek_num, Length: 10000, dtype: int64

In [317]:
data['dayofweek_num'].unique()

array([3, 0, 4, 1, 5, 6, 2])

In [318]:
data['dayofweek_name'] = data['payment'].dt.day_name() # note the braces for month names which is different from all other attributes
data['dayofweek_name']

0        Thursday
1          Monday
2          Friday
3         Tuesday
4          Monday
          ...    
9995    Wednesday
9996      Tuesday
9997     Saturday
9998       Friday
9999     Saturday
Name: dayofweek_name, Length: 10000, dtype: object

In [319]:
data['dayofweek_name'].unique()

array(['Thursday', 'Monday', 'Friday', 'Tuesday', 'Saturday', 'Sunday',
       'Wednesday'], dtype=object)

In [320]:
data['is_weekend'] = data['payment'].dt.day_name().apply(lambda x : 1 if x in ['Saturday','Sunday'] else 0)
data['is_weekend']

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    0
9999    1
Name: is_weekend, Length: 10000, dtype: int64

In [321]:
data['is_weekend'].unique()

array([0, 1])

In [322]:
data.dtypes

issue             datetime64[ns]
payment           datetime64[ns]
date                      object
time                      object
y                          int64
q                          int64
sem                        int64
m_num                      int64
m_name                    object
week_num                   int64
d                          int64
dayofweek_num              int64
dayofweek_name            object
is_weekend                 int64
dtype: object

In [323]:
data['timedelta_days'] = data['payment'] - data['issue']
data['timedelta_days']

0      947 days
1      627 days
2      335 days
3      159 days
4      538 days
         ...   
9995   293 days
9996   312 days
9997   253 days
9998   404 days
9999   362 days
Name: timedelta_days, Length: 10000, dtype: timedelta64[ns]

In [324]:
data['timedelta_years'] = (data['payment'] - data['issue']).apply(lambda x : x/np.timedelta64(1,'Y'))
data['timedelta_years']

0       2.592798
1       1.716668
2       0.917199
3       0.435327
4       1.472994
          ...   
9995    0.802207
9996    0.854227
9997    0.692690
9998    1.106114
9999    0.991122
Name: timedelta_years, Length: 10000, dtype: float64

In [325]:
data['timedelta_months'] = (data['payment'] - data['issue']).apply(lambda x : x/np.timedelta64(1,'M'))
data['timedelta_months']

0       31.113575
1       20.600012
2       11.006386
3        5.223927
4       17.675928
          ...    
9995     9.626481
9996    10.250724
9997     8.312286
9998    13.273373
9999    11.893468
Name: timedelta_months, Length: 10000, dtype: float64

In [346]:
data['timedelta_hours'] = (data['payment'] - data['issue']).apply(lambda x : x/np.timedelta64(1,'h'))
data['timedelta_hours']

0       22728.0
1       15048.0
2        8040.0
3        3816.0
4       12912.0
         ...   
9995     7032.0
9996     7488.0
9997     6072.0
9998     9696.0
9999     8688.0
Name: timedelta_hours, Length: 10000, dtype: float64

In [347]:
data['timedelta_minutes'] = (data['payment'] - data['issue']).apply(lambda x : x/np.timedelta64(1,'m'))
data['timedelta_minutes']

0       1363680.0
1        902880.0
2        482400.0
3        228960.0
4        774720.0
          ...    
9995     421920.0
9996     449280.0
9997     364320.0
9998     581760.0
9999     521280.0
Name: timedelta_minutes, Length: 10000, dtype: float64

In [348]:
data['timedelta_seconds'] = (data['payment'] - data['issue']).apply(lambda x : x/np.timedelta64(1,'s'))
data['timedelta_seconds']

0       81820800.0
1       54172800.0
2       28944000.0
3       13737600.0
4       46483200.0
           ...    
9995    25315200.0
9996    26956800.0
9997    21859200.0
9998    34905600.0
9999    31276800.0
Name: timedelta_seconds, Length: 10000, dtype: float64

In [326]:
data['hour'] = data['payment'].dt.hour
data['hour']

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: hour, Length: 10000, dtype: int64

In [327]:
data['minute'] = data['payment'].dt.minute
data['minute']

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: minute, Length: 10000, dtype: int64

In [328]:
data['second'] = data['payment'].dt.second
data['second']

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: second, Length: 10000, dtype: int64

In [329]:
datetime.datetime.today() # Not pandas datetime # Python DateTime # Data Accessor will not work

datetime.datetime(2022, 12, 22, 17, 44, 49, 219806)

In [330]:
datetime.datetime.today().date()

datetime.date(2022, 12, 22)

In [331]:
datetime.datetime.today().day

22

In [332]:
datetime.datetime.today().month

12

In [333]:
datetime.datetime.today().year

2022

In [334]:
(datetime.datetime.today() - data['payment'])

0      2534 days 17:44:49.286960
1      2523 days 17:44:49.286960
2      3009 days 17:44:49.286960
3      2522 days 17:44:49.286960
4      2537 days 17:44:49.286960
                  ...           
9995   4432 days 17:44:49.286960
9996   2522 days 17:44:49.286960
9997   2567 days 17:44:49.286960
9998   2547 days 17:44:49.286960
9999   2532 days 17:44:49.286960
Name: payment, Length: 10000, dtype: timedelta64[ns]

In [335]:
(datetime.datetime.today() - data['payment']).apply(lambda x : x/np.timedelta64(1,'Y'))

0        6.939881
1        6.909764
2        8.240387
3        6.907026
4        6.948095
          ...    
9995    12.136428
9996     6.907026
9997     7.030232
9998     6.975474
9999     6.934405
Name: payment, Length: 10000, dtype: float64

In [336]:
(datetime.datetime.today() - data['payment']).apply(lambda x : x/np.timedelta64(1,'M'))

0        83.278571
1        82.917167
2        98.884641
3        82.884313
4        83.377136
           ...    
9995    145.637141
9996     82.884313
9997     84.362782
9998     83.705685
9999     83.212861
Name: payment, Length: 10000, dtype: float64

In [337]:
(datetime.datetime.today() - data['payment']).apply(lambda x : x/np.timedelta64(1,'D'))

0       2534.739464
1       2523.739464
2       3009.739464
3       2522.739464
4       2537.739464
           ...     
9995    4432.739464
9996    2522.739464
9997    2567.739464
9998    2547.739464
9999    2532.739464
Name: payment, Length: 10000, dtype: float64

### Add time delta

In [338]:
data['add_day'] = data['payment'] + np.timedelta64(1,'D')
data[['payment','add_day']]

payment    add_day
0    2016-01-14 2016-01-15
1    2016-01-25 2016-01-26
2    2014-09-26 2014-09-27
3    2016-01-26 2016-01-27
4    2016-01-11 2016-01-12
...         ...        ...
9995 2010-11-03 2010-11-04
9996 2016-01-26 2016-01-27
9997 2015-12-12 2015-12-13
9998 2016-01-01 2016-01-02
9999 2016-01-16 2016-01-17

[10000 rows x 2 columns]

In [339]:
data['add_month'] = data['payment'] + np.timedelta64(1,'M')
data[['payment','add_month']]

payment           add_month
0    2016-01-14 2016-02-13 10:29:06
1    2016-01-25 2016-02-24 10:29:06
2    2014-09-26 2014-10-26 10:29:06
3    2016-01-26 2016-02-25 10:29:06
4    2016-01-11 2016-02-10 10:29:06
...         ...                 ...
9995 2010-11-03 2010-12-03 10:29:06
9996 2016-01-26 2016-02-25 10:29:06
9997 2015-12-12 2016-01-11 10:29:06
9998 2016-01-01 2016-01-31 10:29:06
9999 2016-01-16 2016-02-15 10:29:06

[10000 rows x 2 columns]

In [340]:
data['add_week'] = data['payment'] + np.timedelta64(1,'W')
data[['payment','add_week']]

payment   add_week
0    2016-01-14 2016-01-21
1    2016-01-25 2016-02-01
2    2014-09-26 2014-10-03
3    2016-01-26 2016-02-02
4    2016-01-11 2016-01-18
...         ...        ...
9995 2010-11-03 2010-11-10
9996 2016-01-26 2016-02-02
9997 2015-12-12 2015-12-19
9998 2016-01-01 2016-01-08
9999 2016-01-16 2016-01-23

[10000 rows x 2 columns]

In [341]:
data['add_year'] = data['payment'] + np.timedelta64(1,'Y')
data[['payment','add_year']]

payment            add_year
0    2016-01-14 2017-01-13 05:49:12
1    2016-01-25 2017-01-24 05:49:12
2    2014-09-26 2015-09-26 05:49:12
3    2016-01-26 2017-01-25 05:49:12
4    2016-01-11 2017-01-10 05:49:12
...         ...                 ...
9995 2010-11-03 2011-11-03 05:49:12
9996 2016-01-26 2017-01-25 05:49:12
9997 2015-12-12 2016-12-11 05:49:12
9998 2016-01-01 2016-12-31 05:49:12
9999 2016-01-16 2017-01-15 05:49:12

[10000 rows x 2 columns]

In [342]:
data['add_hour'] = data['payment'] + np.timedelta64(1,'h')
data[['payment','add_hour']]

payment            add_hour
0    2016-01-14 2016-01-14 01:00:00
1    2016-01-25 2016-01-25 01:00:00
2    2014-09-26 2014-09-26 01:00:00
3    2016-01-26 2016-01-26 01:00:00
4    2016-01-11 2016-01-11 01:00:00
...         ...                 ...
9995 2010-11-03 2010-11-03 01:00:00
9996 2016-01-26 2016-01-26 01:00:00
9997 2015-12-12 2015-12-12 01:00:00
9998 2016-01-01 2016-01-01 01:00:00
9999 2016-01-16 2016-01-16 01:00:00

[10000 rows x 2 columns]

In [343]:
data['add_minute'] = data['payment'] + np.timedelta64(1,'m')
data[['payment','add_minute']]

payment          add_minute
0    2016-01-14 2016-01-14 00:01:00
1    2016-01-25 2016-01-25 00:01:00
2    2014-09-26 2014-09-26 00:01:00
3    2016-01-26 2016-01-26 00:01:00
4    2016-01-11 2016-01-11 00:01:00
...         ...                 ...
9995 2010-11-03 2010-11-03 00:01:00
9996 2016-01-26 2016-01-26 00:01:00
9997 2015-12-12 2015-12-12 00:01:00
9998 2016-01-01 2016-01-01 00:01:00
9999 2016-01-16 2016-01-16 00:01:00

[10000 rows x 2 columns]

In [344]:
data['add_second'] = data['payment'] + np.timedelta64(1,'s')
data[['payment','add_second']]

payment          add_second
0    2016-01-14 2016-01-14 00:00:01
1    2016-01-25 2016-01-25 00:00:01
2    2014-09-26 2014-09-26 00:00:01
3    2016-01-26 2016-01-26 00:00:01
4    2016-01-11 2016-01-11 00:00:01
...         ...                 ...
9995 2010-11-03 2010-11-03 00:00:01
9996 2016-01-26 2016-01-26 00:00:01
9997 2015-12-12 2015-12-12 00:00:01
9998 2016-01-01 2016-01-01 00:00:01
9999 2016-01-16 2016-01-16 00:00:01

[10000 rows x 2 columns]

In [349]:
data.dtypes

issue                 datetime64[ns]
payment               datetime64[ns]
date                          object
time                          object
y                              int64
q                              int64
sem                            int64
m_num                          int64
m_name                        object
week_num                       int64
d                              int64
dayofweek_num                  int64
dayofweek_name                object
is_weekend                     int64
timedelta_days       timedelta64[ns]
timedelta_years              float64
timedelta_months             float64
hour                           int64
minute                         int64
second                         int64
add_day               datetime64[ns]
add_month             datetime64[ns]
add_week              datetime64[ns]
add_year              datetime64[ns]
add_hour              datetime64[ns]
add_minute            datetime64[ns]
add_second            datetime64[ns]
t